version: '3'

services:
    web-service:
        image: devopsdockeruh/simple-web-service
        build: .
        volumes: 
          - ./data/log.txt:/usr/src/app/text.log
        container_name: web