version: '3'

services: 
  redis_db:
      image: redis
      ports: 
        - 6379:6379
  db:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment: 
        - POSTGRES_PASSWORD=dbpw
        - POSTGRES_USER=user
        - POSTGRES_DB=mydb
      ports: 
        - 5432
  backend:
      image: back
      ports: 
        - 8080:8080
      environment: 
        - REDIS_HOST=redis_db
        - POSTGRES_HOST=db
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=dbpw
        - POSTGRES_DATABASE=mydb
      restart: unless-stopped
      depends_on: 
        - db
  frontend: 
      image: front
      ports: 
        - 5000:5000
 